import { existsSync, readFileSync, rmdirSync } from 'fs';

import { convertFromDirectory } from '../../index';

describe('Cast primitive types', () => {
  const typeOutputDirectory = './src/__tests__/cast/interfaces';

  beforeAll(() => {
    if (existsSync(typeOutputDirectory)) {
      rmdirSync(typeOutputDirectory, { recursive: true });
    }
  });

  test('casts all variations from file', async () => {
    const result = await convertFromDirectory({
      schemaDirectory: './src/__tests__/cast/schemas',
      honorCastTo: ['string', 'number'],
      typeOutputDirectory
    });

    expect(result).toBe(true);

    const oneContent = readFileSync(`${typeOutputDirectory}/One.ts`).toString();

    expect(oneContent).toBe(
      `/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Numbers {
  bool: number;
  day: number;
}

export interface Strings {
  num: string;
}
`
    );
  });

  test('cast only a single type from file', async () => {
    const result = await convertFromDirectory({
      schemaDirectory: './src/__tests__/cast/schemas',
      honorCastTo: ['number'],
      typeOutputDirectory
    });

    expect(result).toBe(true);

    const oneContent = readFileSync(`${typeOutputDirectory}/One.ts`).toString();

    expect(oneContent).toBe(
      `/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Numbers {
  bool: number;
  day: number;
}

export interface Strings {
  num: number;
}
`
    );
  });
});
