import { convertFromDirectory } from '../../index';
import { readFileSync } from 'fs';

test('02.fromFiles', async () => {
  const typeOutputDirectory = './src/__tests__/02/models';
  const result = await convertFromDirectory({
    schemaDirectory: './src/__tests__/02/schemas',
    typeOutputDirectory
  });

  expect(result).toBe(true);

  const indexContent = readFileSync(`${typeOutputDirectory}/index.ts`).toString();

  expect(indexContent).toBe(
    `/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export * from './FooBar';
export * from './One';
`
  );
  const oneContent = readFileSync(`${typeOutputDirectory}/One.ts`).toString();

  expect(oneContent).toBe(
    `/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * a test schema definition
 */
export interface TestSchema {
  'yellow.flower'?: string;
  name?: string;
  propertyName1: boolean;
}
`
  );

  const fooBarContent = readFileSync(`${typeOutputDirectory}/FooBar.ts`).toString();

  expect(fooBarContent).toBe(`/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface Bar {
  /**
   * Id
   */
  id: number;
}

export interface Foo {
  /**
   * Bar
   */
  bar: Bar;
  /**
   * Id
   */
  id: number;
}
`);
});
