import { existsSync, readFileSync, rmdirSync } from "fs";
import { convertFromDirectory } from "../..";

describe('test if an interface gets extended', () => {
  const typeOutputDirectory = './src/__tests__/extends/interfaces';

  beforeAll(() => {
    if (existsSync(typeOutputDirectory)) {
      rmdirSync(typeOutputDirectory, { recursive: true });
    }
  });

  test('does reading form files work', async () => {
    const result = await convertFromDirectory({
      schemaDirectory: './src/__tests__/extends/schemas',
      typeOutputDirectory
    });

    expect(result).toBe(true);

    expect(existsSync(`${typeOutputDirectory}/Workspace.ts`)).toBe(true);


    const readmeContent = readFileSync(`${typeOutputDirectory}/Portfolio.ts`).toString();

    expect(readmeContent).toBe(`/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { IWorkspace } from '.';

export interface IPortfolio extends IWorkspace {
  john?: string;
}
`);
  });

});
