import { existsSync, readFileSync, rmdirSync } from 'fs';

import { convertFromDirectory } from '../../index';

describe('Primitive Types', () => {
  const typeOutputDirectory = './src/__tests__/primitiveTypes/interfaces';
  beforeEach(() => {
    if (existsSync(typeOutputDirectory)) {
      rmdirSync(typeOutputDirectory, { recursive: true });
    }
  });

  test('a good example schema', async () => {
    const result = await convertFromDirectory({
      schemaDirectory: './src/__tests__/primitiveTypes/schemas',
      typeOutputDirectory
    });

    expect(result).toBe(true);

    const readmeContent = readFileSync(`${typeOutputDirectory}/Email.ts`).toString();

    expect(readmeContent).toBe(`/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface CompanySchema {
  email?: Email;
}

export type Email = string;

export interface UserSchema {
  email: Email;
}
`);
  });
});
