import { convertFromDirectory } from '../../index';
import { readFileSync } from 'fs';

test('11.tmp', async () => {
  const typeOutputDirectory = './src/__tests__/11/models';
  const result = await convertFromDirectory({
    schemaDirectory: './src/__tests__/11/schemas',
    typeOutputDirectory,
    sortPropertiesByName: false
  });

  expect(result).toBe(true);

  const oneContent = readFileSync(`${typeOutputDirectory}/One.ts`).toString();

  expect(oneContent).toBe(
    `/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface thingSchema {
  thing: string;
}
`
  );
});
