/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { Person } from '../subDir';
import { Item } from '..';

export interface Employee {
  personalDetails: Person;
  pet: Item;
}
