import { convertFromDirectory } from '../index';
import { readFileSync } from 'fs';

test('03.array', async () => {
  const typeOutputDirectory = './src/__tests__/03/models';
  const result = await convertFromDirectory({
    schemaDirectory: './src/__tests__/03/schemas',
    typeOutputDirectory
  });

  expect(result).toBe(true);

  const oneContent = readFileSync(`${typeOutputDirectory}/One.ts`).toString();

  expect(oneContent).toBe(
    `/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * Item
 */
export interface Item {
  /**
   * name
   */
  name: string;
}

/**
 * a test schema definition
 */
export interface Test {
  /**
   * items
   */
  items?: Item[];
  /**
   * name
   */
  name?: string;
  /**
   * propertyName1
   */
  propertyName1: boolean;
}

/**
 * A list of Test object
 */
export type TestList = Test[];
`
  );
});
