import { convertFromDirectory } from '../index';
import { readFileSync } from 'fs';

test('04.multipleFiles', async () => {
  const interfaceDirectory = './src/__tests__/04/models';

  const result = await convertFromDirectory({
    schemaDirectory: './src/__tests__/04/schemas',
    interfaceDirectory
  });

  expect(result).toBe(true);

  const oneContent = readFileSync(`${interfaceDirectory}/One.ts`).toString();

  expect(oneContent).toBe(
    `/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { Person } from '.';

/**
 * Item
 */
export interface Item {
  /**
   * name
   */
  name: string;
  /**
   * Male Zebra
   */
  maleZebra?: Zebra;
  /**
   * Female Zebra
   */
  femaleZebra?: Zebra;
}

/**
 * A list of People
 */
export type People = Person[];

/**
 * a test schema definition
 */
export interface Test {
  /**
   * name
   */
  name?: string;
  /**
   * propertyName1
   */
  propertyName1: boolean;
  /**
   * A list of People
   */
  people?: People;
}

/**
 * Zebra
 */
export interface Zebra {
  /**
   * name
   */
  name?: string;
}
`
  );
});
