// import Joi from 'joi';

import {
  convertFromDirectory
  // convertSchema, Settings,
} from '../index';
import { readFileSync } from 'fs';

test('06.alternatives', async () => {
  const interfaceDirectory = './src/__tests__/06/models';
  const result = await convertFromDirectory({
    schemaDirectory: './src/__tests__/06/schemas',
    interfaceDirectory,
    sortPropertiesByName: false
  });

  expect(result).toBe(true);

  const oneContent = readFileSync(`${interfaceDirectory}/One.ts`).toString();
  expect(oneContent).toBe(
    `/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * a description for basic
 */
export type Basic = number | string;

/**
 * Other
 */
export interface Other {
  /**
   * other
   */
  other?: string;
}

/**
 * a test schema definition
 */
export interface Test {
  /**
   * name
   */
  name?: string;
  /**
   * value
   */
  value?: Thing | Other;
  /**
   * a description for basic
   */
  basic?: Basic;
}

/**
 * A list of Test object
 */
export type TestList = (boolean | string)[];

/**
 * Thing
 */
export interface Thing {
  /**
   * thing
   */
  thing: string;
}
`
  );
});
