export class AssertionCriteria {
  private static autoGenHeader = `/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

`;

  private static oneContentGeneratedModel = `

/**
 * Item
 */
export interface Item {
  /**
   * Female Zebra
   */
  femaleZebra?: Zebra;
  /**
   * Male Zebra
   */
  maleZebra?: Zebra;
  /**
   * name
   */
  name: string;
}

/**
 * A list of People
 */
export type People = Person[];

/**
 * a test schema definition
 */
export interface Test {
  /**
   * name
   */
  name?: string;
  /**
   * A list of People
   */
  people?: People;
  /**
   * propertyName1
   */
  propertyName1: boolean;
}

/**
 * Zebra
 */
export interface Zebra {
  /**
   * name
   */
  name?: string;
}
`;

  public static oneContentFlatOrIndexAll =
    AssertionCriteria.autoGenHeader + `import { Person } from '.';` + AssertionCriteria.oneContentGeneratedModel;

  public static oneContentTree =
    AssertionCriteria.autoGenHeader + `import { Person } from './subDir';` + AssertionCriteria.oneContentGeneratedModel;

  public static personContentModel = `

/**
 * Person
 */
export interface Person {
  /**
   * address
   */
  address: Address;
  /**
   * firstName
   */
  firstName: string;
  /**
   * lastName
   */
  lastName: string;
}
`;

  public static personContentTree =
    AssertionCriteria.autoGenHeader + `import { Address } from '.';` + AssertionCriteria.personContentModel;

  public static personRootIndexContent =
    AssertionCriteria.autoGenHeader + `import { Address } from '..';` + AssertionCriteria.personContentModel;

  public static defaultRootIndexContent =
    AssertionCriteria.autoGenHeader +
    `export * from './One';
`;

  public static subDirIndexContent =
    AssertionCriteria.autoGenHeader +
    `export * from './Address';
export * from './Person';
`;

  public static flattenedRootIndexContent =
    AssertionCriteria.autoGenHeader +
    `export * from './One';
export * from './Address';
export * from './Person';
export * from './Employee';
`;

  public static indexAllToRootIndexContent =
    AssertionCriteria.autoGenHeader +
    `export * from './One';
export * from './subDir/Address';
export * from './subDir/Person';
export * from './subDir2/Employee';
`;

  public static addressContent =
    AssertionCriteria.autoGenHeader +
    `/**
 * Address
 */
export interface Address {
  /**
   * Suburb
   */
  Suburb: string;
  /**
   * addressLineNumber1
   */
  addressLineNumber1: string;
}
`;

  public static employeeContentModel = `

/**
 * Employee
 */
export interface Employee {
  /**
   * personalDetails
   */
  personalDetails: Person;
  /**
   * pet
   */
  pet: Item;
}
`;

  public static employeeContentTree =
    AssertionCriteria.autoGenHeader +
    `import { Person } from '../subDir';\nimport { Item } from '..';` +
    AssertionCriteria.employeeContentModel;

  public static employeeContentFlattened =
    AssertionCriteria.autoGenHeader + `import { Person, Item } from '.';` + AssertionCriteria.employeeContentModel;

  public static employeeRootIndexContent =
    AssertionCriteria.autoGenHeader + `import { Person, Item } from '..';` + AssertionCriteria.employeeContentModel;

  public static subDir2IndexContent =
    AssertionCriteria.autoGenHeader +
    `export * from './Employee';
`;
}
