export class AssertionCriteria {
  private static autoGenHeader = `/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

`;

  private static oneContentGeneratedModel = `

/**
 * Item
 */
export interface Item {
  /**
   * Female Zebra
   */
  femaleZebra?: Zebra;
  /**
   * Male Zebra
   */
  maleZebra?: Zebra;
  /**
   * name
   */
  name: string;
}

/**
 * A list of People
 */
export type People = Person[];

/**
 * a test schema definition
 */
export interface Test {
  /**
   * name
   */
  name?: string;
  /**
   * A list of People
   */
  people?: People;
  /**
   * propertyName1
   */
  propertyName1: boolean;
}

/**
 * Zebra
 */
export interface Zebra {
  /**
   * name
   */
  name?: string;
}
`;

  public static oneContentFlatOrIndexAll =
    AssertionCriteria.autoGenHeader + `import { Person } from '.';` + AssertionCriteria.oneContentGeneratedModel;

  public static oneContentTree =
    AssertionCriteria.autoGenHeader + `import { Person } from './subDir';` + AssertionCriteria.oneContentGeneratedModel;

  public static personContent =
    AssertionCriteria.autoGenHeader +
    `/**
 * Person
 */
export interface Person {
  /**
   * firstName
   */
  firstName: string;
  /**
   * lastName
   */
  lastName: string;
}
`;

  public static defaultRootIndexContent =
    AssertionCriteria.autoGenHeader +
    `export * from './One';
 `;

  public static subDirIndexContent =
    AssertionCriteria.autoGenHeader +
    `export * from './Person';
 `;

  public static flattenedRootIndexContent =
    AssertionCriteria.autoGenHeader +
    `export * from './One';
export * from './Person';
`;

  public static indexAllToRootIndexContent =
    AssertionCriteria.autoGenHeader +
    `export * from './One';
export * from './subDir/Person';
`;
}
