export class AssertionCriteria {
  private static autoGenHeader = `/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

`;

  private static oneContentGeneratedModel = `

export interface Item {
  /**
   * Female Zebra
   */
  femaleZebra?: Zebra;
  /**
   * Male Zebra
   */
  maleZebra?: Zebra;
  name: string;
}

/**
 * A list of People
 */
export type People = Person[];

/**
 * a test schema definition
 */
export interface Test {
  name?: string;
  /**
   * A list of People
   */
  people?: People;
  propertyName1: boolean;
}

export interface Zebra {
  name?: string;
}
`;

  public static oneContentFlatOrIndexAll =
    AssertionCriteria.autoGenHeader + `import { Person } from '.';` + AssertionCriteria.oneContentGeneratedModel;

  public static oneContentTree =
    AssertionCriteria.autoGenHeader + `import { Person } from './subDir';` + AssertionCriteria.oneContentGeneratedModel;

  public static personContentModel = `

export interface Person {
  address: Address;
  firstName: string;
  lastName: string;
}
`;

  public static personContentTree =
    AssertionCriteria.autoGenHeader + `import { Address } from '.';` + AssertionCriteria.personContentModel;

  public static personRootIndexContent =
    AssertionCriteria.autoGenHeader + `import { Address } from '..';` + AssertionCriteria.personContentModel;

  public static defaultRootIndexContent =
    AssertionCriteria.autoGenHeader +
    `export * from './One';
`;

  public static subDirIndexContent =
    AssertionCriteria.autoGenHeader +
    `export * from './Address';
export * from './Person';
`;

  public static flattenedRootIndexContent =
    AssertionCriteria.autoGenHeader +
    `export * from './One';
export * from './Address';
export * from './Person';
export * from './Employee';
`;

  public static indexAllToRootIndexContent =
    AssertionCriteria.autoGenHeader +
    `export * from './One';
export * from './subDir/Address';
export * from './subDir/Person';
export * from './subDir2/Employee';
`;

  public static addressContent =
    AssertionCriteria.autoGenHeader +
    `export interface Address {
  Suburb: string;
  addressLineNumber1: string;
}
`;

  public static employeeContentModel = `

export interface Employee {
  personalDetails: Person;
  pet: Item;
}
`;

  public static employeeContentTree =
    AssertionCriteria.autoGenHeader +
    `import { Person } from '../subDir';\nimport { Item } from '..';` +
    AssertionCriteria.employeeContentModel;

  public static employeeContentFlattened =
    AssertionCriteria.autoGenHeader + `import { Person, Item } from '.';` + AssertionCriteria.employeeContentModel;

  public static employeeRootIndexContent =
    AssertionCriteria.autoGenHeader + `import { Person, Item } from '..';` + AssertionCriteria.employeeContentModel;

  public static subDir2IndexContent =
    AssertionCriteria.autoGenHeader +
    `export * from './Employee';
`;
}
