import { existsSync, readFileSync, rmdirSync } from 'fs';

import { convertFromDirectory } from '../../index';

describe('description', () => {
  const typeOutputDirectory = './src/__tests__/description/interfaces';

  beforeAll(() => {
    if (existsSync(typeOutputDirectory)) {
      rmdirSync(typeOutputDirectory, { recursive: true });
    }
  });

  test('generates proper descriptions', async () => {
    const result = await convertFromDirectory({
      schemaDirectory: './src/__tests__/description/schemas',
      typeOutputDirectory,
      sortPropertiesByName: false,
      commentEverything: true
    });

    expect(result).toBe(true);

    const oneContent = readFileSync(`${typeOutputDirectory}/One.ts`).toString();
    expect(oneContent).toBe(
      `/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * A simple description
 */
export interface Example {
  /**
   * thing
   */
  thing: string;
}

/**
 * This is a long description.
 * There are many lines!
 *
 * And more here!
 */
export interface ExampleLong {
  /**
   * another
   */
  another: string;
}

/**
 * NoComment
 */
export interface NoComment {
  /**
   * more
   */
  more: string;
}
`
    );
  });
});
