import { existsSync, readFileSync, rmdirSync } from 'fs';

import { convertFromDirectory, convertSchema } from '../../index';
import Joi from 'joi';

describe('description', () => {
  const typeOutputDirectory = './src/__tests__/description/interfaces';

  beforeAll(() => {
    if (existsSync(typeOutputDirectory)) {
      rmdirSync(typeOutputDirectory, { recursive: true });
    }
  });

  test('generates proper descriptions', async () => {
    const result = await convertFromDirectory({
      schemaDirectory: './src/__tests__/description/schemas',
      typeOutputDirectory,
      sortPropertiesByName: false,
      commentEverything: true
    });

    expect(result).toBe(true);

    const oneContent = readFileSync(`${typeOutputDirectory}/One.ts`).toString();
    expect(oneContent).toBe(
      `/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * A schema with an example
 *
 * @example
 * {
 *   "more": "world"
 * }
 */
export interface DescriptionAndExample {
  /**
   * more
   */
  more: string;
}

/**
 * A schema with two examples
 *
 * @example
 * {
 *   "more": "world"
 * }
 * @example
 * {
 *   "more": "coffee"
 * }
 */
export interface DescriptionAndExamples {
  /**
   * more
   */
  more: string;
}

/**
 * A schema with a short example
 *
 * @example One liner
 */
export interface DescriptionAndShortExample {
  /**
   * more
   */
  more: string;
}

export interface DisableDescription {
  /**
   * thing
   */
  thing: string;
}

/**
 * DisableDescriptionObject
 */
export interface DisableDescriptionObject {
  /**
   * withDescription
   */
  withDescription?: {
    /**
     * A simple description
     */
    [x: string]: Example;
  };
  /**
   * withoutDescription
   */
  withoutDescription?: {
    [x: string]: Example;
  };
}

/**
 * A simple description
 */
export interface Example {
  /**
   * thing
   */
  thing: string;
}

/**
 * ExampleAlternatives
 */
export interface ExampleAlternatives {
  /**
   * alt1
   */
  alt1?:
    /**
     * A string
     */
    | string
    /**
     * A number
     */
    | number
    /**
     * An object
     */
    | {
      /**
       * A value
       */
      value?: string;
    }
    /**
     * An array
     */
    | string[]
    /**
     * A tuple
     */
    | [number,
      /**
       * A string
       */
       string,
      Item?
    ] | null
    /**
     * Another tuple
     */
    | [
      /**
       * A tuple number
       */
      number,
      string
    ]
    /**
     * A tuple with one item
     */
    | [
      /**
       * A tuple number
       */
      number
    ];
}

/**
 * ExampleAlternativesRaw
 */
export type ExampleAlternativesRaw =
  /**
   * A string
   */
  | string
  /**
   * A number
   */
  | number
  /**
   * An object
   */
  | {
    /**
     * A value
     */
    value?: string;
  }
  /**
   * An array
   */
  | string[]
  /**
   * A tuple
   */
  | [number,
    /**
     * A string
     */
     string,
    Item?
  ] | null
  /**
   * Another tuple
   */
  | [
    /**
     * A tuple number
     */
    number,
    string
  ]
  /**
   * A tuple with one item
   */
  | [
    /**
     * A tuple number
     */
    number
  ];

/**
 * This is a long indented description.
 * There are many lines!
 *
 * And more here!
 */
export interface ExampleLong {
  /**
   * Another description
   */
  another: string;
  /**
   * Not indented description
   */
  noIndent?: string;
  /**
   * Badly indented description
   *     What a line
   */
  badIndent?: string;
  /**
   * Another badly indented description
   *   What a line
   */
  badIndent2?: string;
}

/**
 * ExampleNewLine
 *
 * @example
 * I have many
 * lines!
 */
export interface ExampleNewLine {
  /**
   * more
   */
  more: string;
}

/**
 * Item
 */
export interface Item {
  /**
   * name
   */
  name: string;
}

/**
 * NoComment
 */
export interface NoComment {
  /**
   * more
   */
  more: string;
}
`
    );
  });

  it('Test JsDoc example spacing', function () {
    {
      const converted = convertSchema(
        {},
        Joi.object({
          hello: Joi.string()
        }).example({
          hello: 'world'
        }),
        'HelloTest'
      );
      expect(converted).toBeDefined();
      expect(converted?.content).toEqual(`/**
 * @example
 * {
 *   "hello": "world"
 * }
 */
export interface HelloTest {
  hello?: string;
}`);
    }

    {
      const converted = convertSchema(
        {},
        Joi.object({
          hello: Joi.string()
        })
          .description('A simple description')
          .example({
            hello: 'world'
          }),
        'HelloTest'
      );
      expect(converted).toBeDefined();
      expect(converted?.content).toEqual(`/**
 * A simple description
 *
 * @example
 * {
 *   "hello": "world"
 * }
 */
export interface HelloTest {
  hello?: string;
}`);
    }
  });
});
