/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

import { Address } from '.';

export interface Person {
  address: Address;
  firstName: string;
  lastName: string;
}
