import { convertFromDirectory } from '../../index';
import { readFileSync } from 'fs';

test('06.alternatives', async () => {
  const typeOutputDirectory = './src/__tests__/06/models';
  const result = await convertFromDirectory({
    schemaDirectory: './src/__tests__/06/schemas',
    typeOutputDirectory,
    sortPropertiesByName: false
  });

  expect(result).toBe(true);

  const oneContent = readFileSync(`${typeOutputDirectory}/One.ts`).toString();
  expect(oneContent).toBe(
    `/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

/**
 * a description for basic
 */
export type Basic = number | string;

export interface Other {
  other?: string;
}

/**
 * a test schema definition
 */
export interface Test {
  name?: string;
  value?: Thing | Other;
  /**
   * a description for basic
   */
  basic?: Basic;
}

/**
 * A list of Test object
 */
export type TestList = (boolean | string)[];

export interface Thing {
  thing: string;
}
`
  );
});
